title: Dealing With Change
description: Have you ever feared change? This blog will show you  why one should not fear change.
remote_theme: 
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
