name: Run Quote Generator

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Script
      run: python quote_generator.py
      
     - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add motivational_quote.txt
          git commit -m "Update motivational quote [skip ci]"
          git push
