name: Run Quote Generator

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        run: python quote_generator.py

      - name: Update README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          - name: Update README
  run: |
    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    git remote set-url origin "https://username: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@github.com/23W-GBAC/AmaAdusei.git"
    git add quote.txt
    git commit -m "Update random quote [skip ci]"
    git push

          git add quote.txt
          git commit -m "Update random quote [skip ci]"
          git push

